from typing import Optional, List, Dict
from dataclasses import dataclass, field
from pydantic import BaseModel

class BrandProfile(BaseModel):
    """
    Represents a brand's visual identity and tone.
    """
    id: str
    name: str
    primary_color: str
    secondary_color: str
    background_color: str
    text_color: str
    font_heading: str
    font_body: str
    logo_filename: Optional[str] = None
    handle: Optional[str] = None
    tone_keywords: str
    tagline: Optional[str] = None
    assets_dir: str

@dataclass
class SlideScript:
    """
    The generated content and visual instructions for a single slide.
    """
    index: int
    slide_type: str  # hook | content | stat | quote | cta
    headline: str
    body_text: Optional[str]
    visual_prompt: Optional[str]  # None if no AI image needed
    visual_style_note: Optional[str]

@dataclass
class CarouselScript:
    """
    The complete structured script generated by the Content Intelligence Module.
    """
    title: str
    target_audience: str
    slides: List[SlideScript]

@dataclass
class PipelineContext:
    """
    Immutable state object passed through all stages of the generation pipeline.
    """
    job_id: str
    topic: str
    brand: BrandProfile
    slide_count: int
    gemini_model: str
    use_imagen: bool

    # Filled by Content Intelligence Module
    carousel_script: Optional[CarouselScript] = None

    # Filled by Asset Generation Module (map of slide_index -> asset_path)
    generated_assets: Dict[int, str] = field(default_factory=dict)

    # Filled by Composition Engine
    rendered_slides: List[str] = field(default_factory=list)

    # Slides where Imagen failed and fallback was used
    fallback_indices: List[int] = field(default_factory=list)
